// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ301ZC6qCM3Ttmvp_OdCXO59noyck1sM',
    appId: '1:60073568220:web:18c0d23b707c09805f5119',
    messagingSenderId: '60073568220',
    projectId: 'marco-nagy',
    authDomain: 'marco-nagy.firebaseapp.com',
    storageBucket: 'marco-nagy.firebasestorage.app',
    measurementId: 'G-8G6XD0FEDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTW0oN97PZjhNAqe8yEXU79DxIbh45uXE',
    appId: '1:60073568220:android:920b78d8962b7c2f5f5119',
    messagingSenderId: '60073568220',
    projectId: 'marco-nagy',
    storageBucket: 'marco-nagy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEAT1vaBVjrU0rBW99CDp7f3wLT8rmlDQ',
    appId: '1:60073568220:ios:a70bc63d0ba452305f5119',
    messagingSenderId: '60073568220',
    projectId: 'marco-nagy',
    storageBucket: 'marco-nagy.firebasestorage.app',
    iosBundleId: 'com.example.marcoPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEAT1vaBVjrU0rBW99CDp7f3wLT8rmlDQ',
    appId: '1:60073568220:ios:a70bc63d0ba452305f5119',
    messagingSenderId: '60073568220',
    projectId: 'marco-nagy',
    storageBucket: 'marco-nagy.firebasestorage.app',
    iosBundleId: 'com.example.marcoPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ301ZC6qCM3Ttmvp_OdCXO59noyck1sM',
    appId: '1:60073568220:web:5a6cec09e0acc6b95f5119',
    messagingSenderId: '60073568220',
    projectId: 'marco-nagy',
    authDomain: 'marco-nagy.firebaseapp.com',
    storageBucket: 'marco-nagy.firebasestorage.app',
    measurementId: 'G-ZXZVHHM8WE',
  );
}
